export const SERVICES = {
  goals: {
    chatId: 1,
    agentId: "1",
    name: "Goal Mapping",
    description: "Convert your goals into structured roadmaps.",
    icon: "FlagOutlined",
    color: "#001529",
    backgroundColor: "#fff",
    textColor: "#000",
    borderColor: "#000",
  },
  notes: {
    chatId: 2,
    agentId: "6",
    name: "Smart Notes",
    description: "Convert messy notes into structured study material.",
    icon: "FileTextOutlined",
    color: "#001529",
    backgroundColor: "#fff",
    textColor: "#000",
    borderColor: "#000",
  },
  revision: {
    chatId: 3,
    agentId: "2",
    name: "Smart Revision",
    description: "AI asks questions to help active recall.",
    icon: "BulbOutlined",
    color: "#001529",
    backgroundColor: "#fff",
    textColor: "#000",
    borderColor: "#000",
  },
  concepts: {
    chatId: 6,
    agentId: "3",
    name: "Concept Simplifier",
    description: "Explain complex concepts simply.",
    icon: "BookOutlined",
    color: "#001529",
    backgroundColor: "#fff",
    textColor: "#000",
    borderColor: "#000",
  },
  support: {
    chatId: 7,
    agentId: "5",
    name: "Human Support",
    description: "Get help from mentors.",
    icon: "UserOutlined",
    color: "#001529",
    backgroundColor: "#fff",
    textColor: "#000",
    borderColor: "#000",
  },
  resources: {
    chatId: 4,
    agentId: "4",
    name: "Curated Resources",
    description: "Best study material recommended by AI.",
    icon: "BookOutlined",
    color: "#001529",
    backgroundColor: "#fff",
    textColor: "#000",
    borderColor: "#000",
  },
};
